# Generated by Django 3.0.3 on 2020-02-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketProb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blightmodel',
            name='ticket_id',
            field=models.IntegerField(),
        ),
    ]
